spring:
  data:
    elasticsearch:
      cluster-nodes: 192.168.232.200:9300
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ems
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      suffix: .jsp
      prefix: /
server:
  port: 8008
  servlet:
    context-path: /poem
    jsp:
      init-parameters:
        development: true
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:com/baizhi/mapper/*Mapper.xml